language: rust
deploy:
  provider: cargo
  token:
    secure: M7gil5k9J1B47/eBW1qUfgvDOtHyAnSgdfRv7lv1yFCyTGQjYrZ8bqS6TP5zZ/akQBgRYg76guydOZd27b4xk7fXas1tc5EdzvUR+JK8o4wehLy4siJHpKvBGd9ZFHacjTk0s+DZetmJCln3gE/UXHQbHESGb2rIOe6R7gKxtv/AxOVW99ZKxPGBdUU7A96hCrxC/kwe54fvK8Mr2Xf06KWdoylIH/iLd0/H84nMrna/TvTwyqCOIBMI+L1Us2Yu8DVeFiBFuKIdZ2579wiZwlNR3EvOG7XtQyVgPWdnlZCsqTiDYC5FA3np9+H4cs03AAXRh9/RCKzutEE0HXJ+xsfTRw8xYxjHxS10/gY6UOqY0XfwF7eUQyqZBqmxJLyu1+iwhAGkOBhWma75zBHsNoRJdmu+4RuTO19vFXux6RNk7XeTf3/o3ru8WH5vI/5sCRDQkU5kYgkyYe6rYVnCMdUzilQFM1mJED+qPQEc9IGWo9mym6SUhn3gjJK2N2gyOVRwCJOTnWY5pJpkQdWJtMOvyIoFrj/nYx9MVioJwCX7dekxPPmXJgFPb5U1NVZ/qwZFf7xUh3kyVu1nc2Z7Xn4OhmThYRdL3OH5TLcmCls8Pw9OF/1Cj16KRyZ7qpy7fQqJEnr4i/AKm6ISjQBZ8IkwPhRnkSFv5scQFb3KnZE=
  on:
    tags: true

rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: beta
    - rust: nightly
  fast_finish: true

cache: cargo
